### ISSUE TITLE
Error while running `librarian-puppet install`

### ISSUE THREAD

**Issue by seekshiva** [sbadia/vagrant-gitlab#8]
Hi

I was running the commands as instructed in the Readme. When I ran `librarian-puppet install`, I get the following error:

```
/var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/posix.rb:113:in `spawn': No such file or directory - puppet (Errno::ENOENT)
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/posix.rb:113:in `run!'
        from /var/lib/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet.rb:19:in `puppet_version'
        from /var/lib/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet.rb:32:in `puppet_gem_version'
        from /var/lib/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet/source/forge/repo.rb:137:in `check_puppet_module_options'
        from /var/lib/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet/source/forge/repo.rb:83:in `cache_version_unpacked!'
        from /var/lib/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet/source/forge/repo.rb:56:in `install_version!'
        from /var/lib/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet/source/forge.rb:106:in `install!'
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/manifest.rb:101:in `install!'
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:49:in `block in install_manifests'
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `each'
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `install_manifests'
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:39:in `perform_installation'
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:12:in `run'
        from /var/lib/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet/cli.rb:94:in `install!'
        from /var/lib/gems/1.9.1/gems/librarian-puppet-2.0.0/lib/librarian/puppet/cli.rb:69:in `install'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
        from /var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
        from /var/lib/gems/1.9.1/gems/librarian-puppet-2.0.0/bin/librarian-puppet:7:in `<top (required)>'
        from /usr/local/bin/librarian-puppet:23:in `load'
        from /usr/local/bin/librarian-puppet:23:in `<main>'
```

But I don't find a directory named puppet. Can you help?

Thanks

**Comment by manti** [comment]
Same Problem 
/usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/posix.rb:113:in `spawn': No such file or directory - puppet (Errno::ENOENT)
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/posix.rb:113:in `run!'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.1/lib/librarian/puppet.rb:19:in `puppet_version'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.1/lib/librarian/puppet.rb:32:in `puppet_gem_version'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge/repo.rb:137:in `check_puppet_module_options'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge/repo.rb:83:in `cache_version_unpacked!'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge/repo.rb:56:in `install_version!'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge.rb:114:in `install!'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/manifest.rb:101:in `install!'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:49:in `block in install_manifests'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `each'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `install_manifests'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:39:in `perform_installation'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:12:in `run'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.1/lib/librarian/puppet/cli.rb:94:in `install!'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.1/lib/librarian/puppet/cli.rb:69:in `install'
        from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
        from /usr/lib/ruby/gems/1.9.1/gems/librarian-puppet-2.0.1/bin/librarian-puppet:7:in `<top (required)>'
        from /usr/local/bin/librarian-puppet:19:in `load'
        from /usr/local/bin/librarian-puppet:19:in `<main>'

**Comment by sbadia** [comment]
Hi @manti as Milan said in the comment just above, `puppet` must be installed on the machine which run `librarian-puppet`, I'll update the documentation.

**Comment by manti** [comment]
@sbadia yup.

**Comment by mfowlewebs** [comment]
shouldn't the Gemfile declare this Ruby library dependency?

**Comment by sbadia** [comment]
@mfowlewebs it's already the case https://github.com/sbadia/vagrant-gitlab/blob/master/Gemfile#L12 ? :-)
